rules = [
    OrganizeImports,
    DisableSyntax,
    LeakingImplicitClassVal,
    NoValInForComprehension,
    TypeclassWeakening,
    PreferKleisli,
    PreferCatsSyntax,
    SimplifyCatsExpressions,
    PropagateOpaqueType
]

OrganizeImports.targetDialect = Scala3
