rules = [
    PreferKleisli,
    LeakingImplicitClassVal,
    NoValInForComprehension,
    TypeclassWeakening,
    PreferCatsSyntax,
    SimplifyCatsExpressions,
    PreferArrow,
    //PropagateOpaqueType
]

PreferArrow.aggressive = true

OrganizeImports.targetDialect = Scala3

PropagateOpaqueType {
  autoDiscover {
    enabled = true
    topN = 10
    basicTypes = [ "scala/Predef.String#", "scala/Long#", "scala/Float#", "scala/Double#", "scala/Boolean#", "scala/Short#" ]
  }
}